// Persis SCHEMAS.santri di frontend/shared-excel.js -- dipakai KHUSUS untuk Template & Import/
// Export Excel (interchange data mentah), BUKAN untuk form Edit/Lihat (lihat santriSections.js,
// yang sengaja sudah dibuang field legacy-nya). Kolom lama tetap perlu ada di sini supaya file
// Excel lama masih bisa diimport ulang tanpa kehilangan data.
export const SANTRI_EXCEL_SCHEMA = [
  ['id', 'ID internal (boleh kosong, diabaikan saat import)'],
  ['nama_lengkap_akte', 'Nama lengkap sesuai akte'],
  ['nama_lengkap_kk', 'Nama lengkap sesuai KK'],
  ['nama_setelah_diubah', 'Nama setelah diubah'],
  ['nama_panggilan', 'Nama panggilan'],
  ['catatan', 'Catatan'],
  ['password', 'Password login santri'],
  ['no_induk', 'No induk'],
  ['nik', 'NIK'],
  ['jenis_kelamin_singkat', 'Jenis kelamin singkat'],
  ['status', 'Status'],
  ['keterangan_status', 'Keterangan status'],
  ['tempat_tanggal_lahir', 'Tempat tanggal lahir'],
  ['tempat_lahir', 'Tempat lahir'],
  ['tanggal_lahir', 'Tanggal lahir'],
  ['jenis_kelamin', 'Jenis kelamin'],
  ['alamat_sekarang_tempat', 'Alamat sekarang tempat'],
  ['alamat_sekarang_rt', 'Alamat sekarang RT'],
  ['alamat_sekarang_rw', 'Alamat sekarang RW'],
  ['alamat_sekarang_desa', 'Alamat sekarang desa'],
  ['alamat_sekarang_kecamatan', 'Alamat sekarang kecamatan'],
  ['alamat_sekarang_kota', 'Alamat sekarang kota'],
  ['alamat_sekarang_provinsi', 'Alamat sekarang provinsi'],
  ['alamat_sekarang_kode_pos', 'Alamat sekarang kode pos'],
  ['ayah_nama', 'Nama ayah'],
  ['ayah_ttl', 'TTL ayah'],
  ['ayah_pekerjaan', 'Pekerjaan ayah'],
  ['ibu_nama', 'Nama ibu'],
  ['ibu_ttl', 'TTL ibu'],
  ['ibu_pekerjaan', 'Pekerjaan ibu'],
  ['wali_nama', 'Nama wali'],
  ['wali_ttl', 'TTL wali'],
  ['wali_pekerjaan', 'Pekerjaan wali'],
  ['alamat_ktp_tempat', 'Alamat KTP tempat'],
  ['alamat_ktp_rt', 'Alamat KTP RT'],
  ['alamat_ktp_rw', 'Alamat KTP RW'],
  ['alamat_ktp_desa', 'Alamat KTP desa'],
  ['alamat_ktp_kecamatan', 'Alamat KTP kecamatan'],
  ['alamat_ktp_kota', 'Alamat KTP kota'],
  ['alamat_ktp_provinsi', 'Alamat KTP provinsi'],
  ['admin_kk', 'Dokumen KK'],
  ['admin_ktp', 'Dokumen KTP'],
  ['admin_akta', 'Dokumen akta'],
  ['no_hp', 'No HP'],
  ['tanggal_keluar', 'Tanggal keluar'],
  ['infaq_pengajar', 'Infaq pengajar'],
  ['jaminan', 'Jaminan'],
  ['asal_sekolah', 'Asal sekolah'],
  ['golongan_darah', 'Golongan darah (A/B/AB/O/Tidak tahu)'],
  ['riwayat_penyakit', 'Riwayat penyakit / penyakit bawaan'],
  ['alergi', 'Alergi (makanan/obat/lainnya)'],
  ['kebutuhan_khusus', 'Kebutuhan khusus / disabilitas'],
  ['obat_rutin', 'Obat / perawatan rutin'],
  ['catatan_kesehatan', 'Catatan kesehatan lain']
]
